### PR TITLE
Edited Trade

### PR DESCRIPTION
**Pull request by EvanKluger**
Edited the Trade Member Function to update the other tables as well as Trade History

### CODE REVIEW

**Comment by bobleesj** [comment]
Hi Evan, could you please upload the SQL for Trade History perhaps in the README.md file?  Since I do not have the table initialized, I am afraid it will us error.

**Review by bobleesj — COMMENTED** [review]
I see that you have used `trade.buy` but if you go to the `trade` model, there is no ` buy` property. Please double check the model and run the program before making changes.

**Comment by EvanKluger** [comment]
We currently have 4 Tables in the Database Repo names trade_history, accounts, portfolio, and portfolio_history. I updated the files to both correspond with the table what we have in the database and have the SQL commands update the other accounts besides accounts. Inside the trade command, there was sequel line to edit the table Trades. Right now in our database it is written as trade_history on GitHub. It can be named trade_history or trades whichever is fine with me but the sql commands need to line up with what is on the database on GitHub sql files. Not with what is mentioned in the ReadMe. If u want to update the SQL commands or make changes to those create a PR on the database repo. 

I used Trades.buy because I edited the Trades Model on the PR to correspond the the trade type to the way we have it on the Database currently. We don’t need TradeType to be a string because it’s wasted space in the database when it can be a Boolean.

**Comment by EvanKluger** [comment]
Also I think there is a mistake about what Current Balance is inside trades or trade_history. Current Balance refers to money that is inside the account that was not spent yet on stocks/crypto... Inside Trades you had it listed as Total Deposit - Total Withdrawn, but it's not that. Current Balance would be however much money left you have to spend in your account. So lets say you deposit 1000$, that 1000$ goes straight to your current balance. If you buy apple for 200$, your current balance goes to 800, because you now have 800$ left to spend even though technically your account is worth 1000 because 800 cash + 200 apple. Does this make sense?

**Comment by EvanKluger** [comment]
That is why I edited for the SQL commands inside the trade, deposit, and withdraw member functions SQL commands to update the current balance.

That way when making trades or withdrawing you can check to make sure the trade/withdraw is less than a users current balance before excuting.

**Pull request closed without merging**
